### ISSUE TITLE
Problem installing the app

### ISSUE THREAD

**Issue by Lapsol** [Christian1984/go-maptilecache#1]
I've made a clean install of windows 11 and the latest version of FS. But now I got problem installing the FSKeeboard app. It's asking for missing files...

**Comment by Christian1984** [comment]
This is the wrong repo you are reporting this. Could you please head over to either https://discord.fskneeboard.com or https://github.com/Christian1984/vfrmap-for-vr/issues and the report it there, preferably with step-by-step instructions on how to reproduce the issue and screenshots as well. Please also report what FSKneeboard version you are trying to install (version number, zip or exe-installer, free or pro).
